name: Debug GitHub Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Debug Secrets
      run: |
        echo "=== DEBUGGING GITHUB SECRETS ==="
        echo ""
        echo "VERCEL_TOKEN length: ${#VERCEL_TOKEN}"
        echo "VERCEL_TOKEN first 10 chars: ${VERCEL_TOKEN:0:10}..."
        echo "VERCEL_TOKEN last 10 chars: ...${VERCEL_TOKEN: -10}"
        echo ""
        echo "VERCEL_ORG_ID: '$VERCEL_ORG_ID'"
        echo "VERCEL_ORG_ID length: ${#VERCEL_ORG_ID}"
        echo ""
        echo "VERCEL_PROJECT_ID: '$VERCEL_PROJECT_ID'"
        echo "VERCEL_PROJECT_ID length: ${#VERCEL_PROJECT_ID}"
        echo ""
        echo "=== TESTING VERCEL CONNECTION ==="
        
        # Install Vercel CLI
        npm install --global vercel@latest
        
        # Test with explicit values
        echo "Testing with explicit values..."
        vercel whoami --token $VERCEL_TOKEN
        
        echo "Testing project access..."
        vercel project ls --token $VERCEL_TOKEN
        
        echo "Testing specific project..."
        vercel project inspect $VERCEL_PROJECT_ID --token $VERCEL_TOKEN
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
